P6 dwf2024 2
alexysge/alexysge-Proyecto-Desarrollo-Front_2024-2 pull request #2
Opened 2024-03-19 05:30 UTC by alexysge

Práctica 6 terminada

2024-03-26 00:33 UTC, monmm commented on src/app/module/component/category/category.component.html
> +                <tr class="table-success">
No utilizaste la directiva **ngFor**.

2024-03-26 00:36 UTC, monmm commented on src/main.ts
> -bootstrapApplication(AppComponent, appConfig)
Tuviste que volver a iniciar tu proyecto?

2024-03-26 00:40 UTC, monmm requested changes
Hola Alexys!
Por favor utiliza la directiva **ngFor** en tu `category.component.html` para que los elementos se tomen desde el componente.
Y no olvides hacer push a las carpetas _module_ y _shared_.

2024-03-26 00:48 UTC, monmm commented on src/main.ts
> -bootstrapApplication(AppComponent, appConfig)
Ya leí tu comentario en classroom.
Sí por favor, cualquier duda pregunta por Slack o por correo :)

2024-04-05 05:15 UTC, alexysge commented on src/app/module/component/category/category.component.html
> +                <tr class="table-success">
Ya subí los cambios de esta parte

2024-04-06 04:10 UTC, monmm approved these changes

2024-04-06 04:29 UTC, merged